'images in alphabetical order!

enum E_IMG_ALL
	img_null
	
	act_climb_1
	act_climb_2
	act_climb_3
	act_climb_4
	act_dead
	act_dig_1
	act_dig_2
	act_drill_1
	act_drill_2
	act_drill_down_1
	act_drill_down_2
	act_drill_up_1
	act_drill_up_2
	act_fall_1
	act_fall_2
	act_gpick_1
	act_gpick_2
	act_jetpack_1
	act_jetpack_2
	act_jetpack_3
	act_jetpack_4
	act_pick_1
	act_pick_2
	act_saber_1
	act_saber_2
	act_walk_1
	act_walk_2
	act_walk_3
	act_walk_4
	act_wink_1
	act_wink_2
	act_wink_3
	act_wink_4
	
	bg_block_2a
	bg_block_2b
	bg_block_2
	bg_block_2c
	bg_block_2d
	bg_block_2e
	bg_block_2f
	bg_block_2g
	bg_block_2h
	bg_block_3
	bg_border
	bg_check_no
	bg_check_yes
	bg_dungeon
	bg_earth_0
	bg_earth_1
	bg_earth_2
	bg_earth_3
	bg_earth_4
	bg_earth_5
	bg_earth_6
	bg_earth_7
	bg_earth_8
	bg_earth_9
	bg_earth_crafted
	bg_lamp_double_0
	bg_lamp_double_1
	bg_lamp_double_2
	bg_lamp_single_0
	bg_lamp_single_1
	bg_lamp_single_2
	bg_megalift_0
	bg_megalift_1
	bg_megalift_off
	bg_new_block
	bg_shadow
	bg_spidernest1
	bg_spidernest2
	bg_surface_1
	bg_surface_2
	bg_surface_3
	bg_wall_0
	bg_wall_1
	bg_wall_2
	bg_wall_3
	bg_wall_4
	bg_wall_5

	fg_artefact_bone_1
	fg_artefact_bone_2
	fg_artefact_g1
	fg_artefact_g2
	fg_artefact_g3
	fg_artefact_g4
	fg_artefact_ring
	fg_big_rock
	fg_big_stone
	fg_construction_bridge
	fg_construction_ladder
	fg_construction_ladderbridge
	fg_construction_lift_a0
	fg_construction_lift_a1
	fg_construction_lift_b0
	fg_construction_lift_b1
	fg_construction_sign_down
	fg_construction_sign_left
	fg_construction_sign_right
	fg_construction_sign_stop
	fg_construction_sign_up
	fg_explosive_c4_0
	fg_explosive_c4_1
	fg_explosive_dynamite_1
	fg_explosive_dynamite_2
	fg_explosive_dynamite_3
	fg_explosive_dynamite_4
	fg_landscape_flower_1a
	fg_landscape_flower_1b
	fg_landscape_flower_1c
	fg_landscape_flower_2a
	fg_landscape_flower_2b
	fg_landscape_flower_2c
	fg_landscape_flower_3a
	fg_landscape_flower_3b
	fg_landscape_flower_3c
	fg_landscape_flower_4a
	fg_landscape_flower_4b
	fg_landscape_flower_4c
	fg_landscape_gras_1
	fg_landscape_gras_2
	fg_landscape_gras_3
	fg_landscape_pile
	fg_lava_2a
	fg_lava_2
	fg_lava
	fg_monster_0
	fg_monster_1
	fg_monster_2
	fg_object_cole
	fg_object_diamond_blue
	fg_object_diamond_green
	fg_object_diamond_pink
	fg_object_diamond_red
	fg_object_diamond_small_blue
	fg_object_diamond_small_green
	fg_object_diamond_small_pink
	fg_object_emerald_blue
	fg_object_emerald_red
	fg_object_emerald_yellow
	fg_object_gold
	fg_object_iron
	fg_object_lazurite
	fg_object_patrickium
	fg_object_platin
	fg_object_ruby
	fg_object_salt
	fg_object_sapphire
	fg_object_silver
	fg_object_uranium
	fg_object_yorby
	fg_resource_cole
	fg_resource_diamond_blue
	fg_resource_diamond_green
	fg_resource_diamond_pink
	fg_resource_diamond_red
	fg_resource_diamond_small_blue
	fg_resource_diamond_small_green
	fg_resource_diamond_small_pink
	fg_resource_emerald_blue
	fg_resource_emerald_red
	fg_resource_emerald_yellow
	fg_resource_gold
	fg_resource_iron
	fg_resource_lazurite
	fg_resource_patrickium
	fg_resource_platin
	fg_resource_ruby
	fg_resource_salt
	fg_resource_sapphire
	fg_resource_silver
	fg_resource_uranium
	fg_resource_yorbinium
	fg_spidernet_0
	fg_spidernet_1
	fg_spidernet_2
	fg_spidernet_3
	fg_spidernet_4
	fg_tile_damage_1
	fg_tile_damage_2
	fg_tile_damage_3
	fg_tile_damage_4
	fg_tile_deco_0
	fg_tile_deco_1
	fg_tile_deco_2

	ol_health_0
	ol_health_1
	ol_health_2
	ol_health_3
	ol_health_4
	ol_health_5
	ol_health_6
	ol_health_7
	ol_health_8
	ol_item_drill
	ol_item_pick

	img_overflow
end enum
